// This file is auto-generated by @hey-api/openapi-ts

export const $CreateUserRequest = {
  type: "object",
  properties: {
    name: {
      type: "string",
    },
    photoUrl: {
      type: "string",
      format: "url",
    },
  },
  required: ["name"],
} as const;

export const $User = {
  type: "object",
  properties: {
    id: {
      type: "number",
    },
    firebaseUid: {
      type: "string",
      format: "uuid",
    },
    email: {
      type: "string",
      format: "email",
    },
    name: {
      type: "string",
    },
    photoUrl: {
      type: "string",
      format: "url",
    },
    createdAt: {
      format: "date-time",
      type: "string",
    },
    updatedAt: {
      format: "date-time",
      type: "string",
    },
  },
  required: ["id", "firebaseUid", "email", "name", "createdAt", "updatedAt"],
} as const;

export const $ErrorResponse = {
  type: "object",
  properties: {
    statusCode: {
      type: "number",
    },
    timestamp: {
      format: "date-time",
      type: "string",
    },
    path: {
      type: "string",
    },
    message: {
      anyOf: [
        {
          type: "string",
        },
        {
          type: "array",
          items: {
            type: "string",
          },
        },
      ],
    },
  },
  required: ["statusCode", "timestamp", "path", "message"],
} as const;

export const $Vote = {
  type: "object",
  properties: {
    id: {
      type: "number",
    },
    voterId: {
      type: "number",
    },
    postId: {
      type: "number",
    },
    commentId: {
      type: "number",
    },
    isUpvote: {
      type: "boolean",
    },
  },
  required: ["id", "voterId", "isUpvote"],
} as const;

export const $CreateCommentRequest = {
  type: "object",
  properties: {
    content: {
      type: "string",
    },
    parentId: {
      type: "number",
    },
  },
  required: ["content"],
} as const;

export const $Comment = {
  type: "object",
  properties: {
    id: {
      type: "number",
    },
    content: {
      type: "string",
    },
    authorId: {
      type: "number",
    },
    parentId: {
      type: "number",
    },
    children: {
      type: "array",
      items: {
        type: "array",
      },
    },
    postId: {
      type: "number",
    },
    votes: {
      type: "number",
    },
    createdAt: {
      format: "date-time",
      type: "string",
    },
    updatedAt: {
      format: "date-time",
      type: "string",
    },
  },
  required: [
    "id",
    "content",
    "authorId",
    "children",
    "postId",
    "votes",
    "createdAt",
    "updatedAt",
  ],
} as const;

export const $UpdateCommentRequest = {
  type: "object",
  properties: {
    content: {
      type: "string",
    },
  },
} as const;

export const $CreateCommunityRequest = {
  type: "object",
  properties: {
    name: {
      type: "string",
    },
    description: {
      type: "string",
    },
  },
  required: ["name", "description"],
} as const;

export const $Community = {
  type: "object",
  properties: {
    id: {
      type: "number",
    },
    name: {
      type: "string",
    },
    description: {
      type: "string",
    },
    ownerId: {
      type: "number",
    },
    createdAt: {
      format: "date-time",
      type: "string",
    },
    updatedAt: {
      format: "date-time",
      type: "string",
    },
  },
  required: ["id", "name", "description", "ownerId", "createdAt", "updatedAt"],
} as const;

export const $UpdateCommunityRequest = {
  type: "object",
  properties: {
    name: {
      type: "string",
    },
    description: {
      type: "string",
    },
  },
} as const;

export const $Post = {
  type: "object",
  properties: {
    id: {
      type: "number",
    },
    title: {
      type: "string",
    },
    content: {
      type: "string",
    },
    communityId: {
      type: "number",
    },
    communityName: {
      type: "string",
    },
    authorId: {
      type: "number",
    },
    votes: {
      type: "number",
    },
    createdAt: {
      format: "date-time",
      type: "string",
    },
    updatedAt: {
      format: "date-time",
      type: "string",
    },
  },
  required: [
    "id",
    "title",
    "content",
    "communityId",
    "communityName",
    "authorId",
    "votes",
    "createdAt",
    "updatedAt",
  ],
} as const;

export const $CreatePostRequest = {
  type: "object",
  properties: {
    title: {
      type: "string",
    },
    content: {
      type: "string",
    },
  },
  required: ["title", "content"],
} as const;

export const $UpdatePostRequest = {
  type: "object",
  properties: {
    title: {
      type: "string",
    },
    content: {
      type: "string",
    },
  },
} as const;
