// This file is auto-generated by @hey-api/openapi-ts

export const $CreateUserRequest = {
  type: "object",
  properties: {
    name: {
      type: "string",
    },
    photoUrl: {
      type: "string",
      format: "url",
    },
  },
  required: ["name"],
} as const;

export const $User = {
  type: "object",
  properties: {
    id: {
      type: "number",
    },
    firebaseUid: {
      type: "string",
      format: "uuid",
    },
    email: {
      type: "string",
      format: "email",
    },
    name: {
      type: "string",
    },
    photoUrl: {
      type: "string",
      format: "url",
    },
    createdAt: {
      format: "date-time",
      type: "string",
    },
    updatedAt: {
      format: "date-time",
      type: "string",
    },
  },
  required: ["id", "firebaseUid", "email", "name", "createdAt", "updatedAt"],
} as const;

export const $ErrorResponse = {
  type: "object",
  properties: {
    statusCode: {
      type: "number",
    },
    timestamp: {
      format: "date-time",
      type: "string",
    },
    path: {
      type: "string",
    },
    message: {
      anyOf: [
        {
          type: "string",
        },
        {
          type: "array",
          items: {
            type: "string",
          },
        },
      ],
    },
  },
  required: ["statusCode", "timestamp", "path", "message"],
} as const;

export const $VoteResponse = {
  type: "object",
  properties: {
    id: {
      type: "number",
    },
    voterId: {
      type: "number",
    },
    postId: {
      type: "number",
    },
    commentId: {
      type: "number",
    },
    replyId: {
      type: "number",
    },
    isUpvote: {
      type: "boolean",
    },
  },
  required: ["id", "voterId", "isUpvote"],
} as const;

export const $CreateCommentRequest = {
  type: "object",
  properties: {
    content: {
      type: "string",
    },
  },
  required: ["content"],
} as const;

export const $CommentResponse = {
  type: "object",
  properties: {
    id: {
      type: "number",
    },
    content: {
      type: "string",
    },
    author: {
      $ref: "#/components/schemas/User",
    },
    postId: {
      type: "number",
    },
    votes: {
      type: "number",
    },
    replyCount: {
      type: "number",
    },
    upvoted: {
      oneOf: [
        {
          type: "boolean",
        },
        {
          type: "null",
        },
      ],
    },
    createdAt: {
      format: "date-time",
      type: "string",
    },
    updatedAt: {
      format: "date-time",
      type: "string",
    },
  },
  required: [
    "id",
    "content",
    "author",
    "postId",
    "votes",
    "replyCount",
    "upvoted",
    "createdAt",
    "updatedAt",
  ],
} as const;

export const $SortBy = {
  type: "string",
  enum: ["new", "top"],
} as const;

export const $Timespan = {
  type: "string",
  enum: ["day", "week", "month", "year", "all-time"],
} as const;

export const $UpdateCommentRequest = {
  type: "object",
  properties: {
    content: {
      type: "string",
    },
  },
} as const;

export const $CreateCommunityRequest = {
  type: "object",
  properties: {
    name: {
      type: "string",
    },
    description: {
      type: "string",
    },
  },
  required: ["name", "description"],
} as const;

export const $Community = {
  type: "object",
  properties: {
    id: {
      type: "number",
    },
    name: {
      type: "string",
    },
    description: {
      type: "string",
    },
    isPrivate: {
      type: "boolean",
    },
    ownerId: {
      type: "number",
    },
    createdAt: {
      format: "date-time",
      type: "string",
    },
    updatedAt: {
      format: "date-time",
      type: "string",
    },
  },
  required: [
    "id",
    "name",
    "description",
    "isPrivate",
    "ownerId",
    "createdAt",
    "updatedAt",
  ],
} as const;

export const $UpdateCommunityRequest = {
  type: "object",
  properties: {
    name: {
      type: "string",
    },
    description: {
      type: "string",
    },
  },
} as const;

export const $PostResponse = {
  type: "object",
  properties: {
    id: {
      type: "number",
    },
    title: {
      type: "string",
    },
    content: {
      type: "string",
    },
    communityId: {
      type: "number",
    },
    communityName: {
      type: "string",
    },
    upvoted: {
      oneOf: [
        {
          type: "boolean",
        },
        {
          type: "null",
        },
      ],
    },
    authorId: {
      type: "number",
    },
    votes: {
      type: "number",
    },
    createdAt: {
      format: "date-time",
      type: "string",
    },
    updatedAt: {
      format: "date-time",
      type: "string",
    },
  },
  required: [
    "id",
    "title",
    "content",
    "communityId",
    "communityName",
    "upvoted",
    "authorId",
    "votes",
    "createdAt",
    "updatedAt",
  ],
} as const;

export const $CreatePostRequest = {
  type: "object",
  properties: {
    title: {
      type: "string",
    },
    content: {
      type: "string",
    },
  },
  required: ["title", "content"],
} as const;

export const $UpdatePostRequest = {
  type: "object",
  properties: {
    title: {
      type: "string",
    },
    content: {
      type: "string",
    },
  },
} as const;

export const $CreateReplyRequest = {
  type: "object",
  properties: {
    content: {
      type: "string",
    },
  },
  required: ["content"],
} as const;

export const $ReplyResponse = {
  type: "object",
  properties: {
    id: {
      type: "number",
    },
    content: {
      type: "string",
    },
    author: {
      $ref: "#/components/schemas/User",
    },
    commentId: {
      type: "number",
    },
    votes: {
      type: "number",
    },
    upvoted: {
      oneOf: [
        {
          type: "boolean",
        },
        {
          type: "null",
        },
      ],
    },
    createdAt: {
      format: "date-time",
      type: "string",
    },
    updatedAt: {
      format: "date-time",
      type: "string",
    },
  },
  required: [
    "id",
    "content",
    "author",
    "commentId",
    "votes",
    "upvoted",
    "createdAt",
    "updatedAt",
  ],
} as const;

export const $UpdateReplyRequest = {
  type: "object",
  properties: {
    content: {
      type: "string",
    },
  },
} as const;
