// This file is auto-generated by @hey-api/openapi-ts

export type CreateUserRequest = {
  name: string;
  photoUrl?: string;
};

export type User = {
  id: number;
  firebaseUid: string;
  email: string;
  name: string;
  photoUrl?: string;
  createdAt: string;
  updatedAt: string;
};

export type ErrorResponse = {
  statusCode: number;
  timestamp: string;
  path: string;
  message: string | Array<string>;
};

export type Vote = {
  id: number;
  voterId: number;
  postId?: number;
  commentId?: number;
  replyId?: number;
  isUpvote: boolean;
};

export type CreateCommentRequest = {
  content: string;
};

export type CommentResponse = {
  id: number;
  content: string;
  author: User;
  postId: number;
  votes: number;
  replyCount: number;
  upvoted: boolean | null;
  createdAt: string;
  updatedAt: string;
};

export type SortBy = "new" | "top";

export const SortBy = {
  NEW: "new",
  TOP: "top",
} as const;

export type Timespan = "day" | "week" | "month" | "year" | "all-time";

export const Timespan = {
  DAY: "day",
  WEEK: "week",
  MONTH: "month",
  YEAR: "year",
  ALL_TIME: "all-time",
} as const;

export type UpdateCommentRequest = {
  content?: string;
};

export type CreateCommunityRequest = {
  name: string;
  description: string;
};

export type Community = {
  id: number;
  name: string;
  description: string;
  isPrivate: boolean;
  ownerId: number;
  createdAt: string;
  updatedAt: string;
};

export type UpdateCommunityRequest = {
  name?: string;
  description?: string;
};

export type PostResponse = {
  id: number;
  title: string;
  content: string;
  communityId: number;
  communityName: string;
  upvoted: boolean | null;
  authorId: number;
  votes: number;
  createdAt: string;
  updatedAt: string;
};

export type CreatePostRequest = {
  title: string;
  content: string;
};

export type UpdatePostRequest = {
  title?: string;
  content?: string;
};

export type CreateReplyRequest = {
  content: string;
};

export type ReplyResponse = {
  id: number;
  content: string;
  author: User;
  commentId: number;
  votes: number;
  upvoted: boolean | null;
  createdAt: string;
  updatedAt: string;
};

export type UpdateReplyRequest = {
  content?: string;
};

export type CreateUserData = {
  requestBody: CreateUserRequest;
};

export type CreateUserResponse = User;

export type GetMyUserDataData = {
  /**
   * The data to include in the response
   */
  include?: Array<"posts" | "votes" | "comments" | "replies">;
};

export type GetMyUserDataResponse = Array<PostResponse | Vote>;

export type GetUserDataData = {
  /**
   * The data to include in the response
   */
  include?: Array<"posts" | "votes" | "comments" | "replies">;
  userId: number;
};

export type GetUserDataResponse = Array<PostResponse | Vote>;

export type GetMeResponse = User | void;

export type GetUserByIdData = {
  id: number;
};

export type GetUserByIdResponse = User;

export type CreateCommentData = {
  postId: number;
  requestBody: CreateCommentRequest;
};

export type CreateCommentResponse = CommentResponse;

export type FindAllCommentsData = {
  postId: number;
  skip?: number;
  sortBy?: SortBy;
  take?: number;
  timespan?: Timespan;
};

export type FindAllCommentsResponse = Array<CommentResponse>;

export type FindCommentByIdData = {
  commentId: number;
};

export type FindCommentByIdResponse = CommentResponse;

export type UpdateCommentData = {
  commentId: number;
  requestBody: UpdateCommentRequest;
};

export type UpdateCommentResponse = CommentResponse;

export type DeleteCommentData = {
  commentId: number;
};

export type DeleteCommentResponse = void;

export type VoteCommentData = {
  id: number;
  isUpvote: boolean;
};

export type VoteCommentResponse = void;

export type UnvoteCommentData = {
  id: number;
};

export type UnvoteCommentResponse = void;

export type CreateCommunityData = {
  requestBody: CreateCommunityRequest;
};

export type CreateCommunityResponse = Community;

export type FindAllCommunitiesResponse = Array<Community>;

export type CheckUserMembershipData = {
  id: number;
};

export type CheckUserMembershipResponse = string;

export type FindUserCommunitiesResponse = Array<Community>;

export type FindOneCommunityData = {
  id: number;
};

export type FindOneCommunityResponse = Community;

export type UpdateCommunityData = {
  id: number;
  requestBody: UpdateCommunityRequest;
};

export type UpdateCommunityResponse = Community;

export type RemoveCommunityData = {
  id: number;
};

export type RemoveCommunityResponse = void;

export type JoinCommunityData = {
  id: number;
};

export type JoinCommunityResponse = void;

export type LeaveCommunityData = {
  id: number;
};

export type LeaveCommunityResponse = void;

export type GetFeedData = {
  skip?: number;
  sortBy?: SortBy;
  take?: number;
  timespan?: Timespan;
};

export type GetFeedResponse = Array<PostResponse>;

export type CreatePostData = {
  communityId: number;
  requestBody: CreatePostRequest;
};

export type CreatePostResponse = PostResponse;

export type FindAllPostsResponse = Array<PostResponse>;

export type FindAllPostsByUserData = {
  skip?: number;
  sortBy?: SortBy;
  take?: number;
  timespan?: Timespan;
  userId: number;
};

export type FindAllPostsByUserResponse = Array<PostResponse>;

export type FindAllPostsInCommunityData = {
  communityId: number;
  skip?: number;
  sortBy?: SortBy;
  take?: number;
  timespan?: Timespan;
};

export type FindAllPostsInCommunityResponse = Array<PostResponse>;

export type FindOnePostData = {
  id: number;
};

export type FindOnePostResponse = PostResponse;

export type UpdatePostData = {
  id: number;
  requestBody: UpdatePostRequest;
};

export type UpdatePostResponse = PostResponse;

export type RemovePostData = {
  id: number;
};

export type RemovePostResponse = void;

export type VotePostData = {
  id: number;
  isUpvote: boolean;
};

export type VotePostResponse = void;

export type UnvotePostData = {
  id: number;
};

export type UnvotePostResponse = void;

export type CreateReplyData = {
  commentId: number;
  requestBody: CreateReplyRequest;
};

export type CreateReplyResponse = ReplyResponse;

export type FindAllRepliesData = {
  commentId: number;
};

export type FindAllRepliesResponse = Array<ReplyResponse>;

export type FindOneReplyData = {
  replyId: number;
};

export type FindOneReplyResponse = ReplyResponse;

export type UpdateReplyData = {
  replyId: number;
  requestBody: UpdateReplyRequest;
};

export type UpdateReplyResponse = ReplyResponse;

export type DeleteReplyData = {
  replyId: number;
};

export type DeleteReplyResponse = void;

export type VoteReplyData = {
  id: number;
  isUpvote: boolean;
};

export type VoteReplyResponse = void;

export type UnvoteReplyData = {
  id: number;
};

export type UnvoteReplyResponse = void;

export type $OpenApiTs = {
  "/users": {
    post: {
      req: CreateUserData;
      res: {
        /**
         * Created
         */
        201: User;
        /**
         * Unauthorized
         */
        401: ErrorResponse;
      };
    };
  };
  "/users/userdata/me": {
    get: {
      req: GetMyUserDataData;
      res: {
        /**
         * OK
         */
        200: Array<PostResponse | Vote>;
        /**
         * Unauthorized
         */
        401: ErrorResponse;
      };
    };
  };
  "/users/userdata/{userId}": {
    get: {
      req: GetUserDataData;
      res: {
        /**
         * OK
         */
        200: Array<PostResponse | Vote>;
        /**
         * Unauthorized
         */
        401: ErrorResponse;
      };
    };
  };
  "/users/me": {
    get: {
      res: {
        /**
         * OK
         */
        200: User;
        /**
         * No content
         */
        204: void;
        /**
         * Unauthorized
         */
        401: ErrorResponse;
      };
    };
  };
  "/users/{id}": {
    get: {
      req: GetUserByIdData;
      res: {
        /**
         * OK
         */
        200: User;
        /**
         * Not found
         */
        404: unknown;
      };
    };
  };
  "/comments/{postId}": {
    post: {
      req: CreateCommentData;
      res: {
        /**
         * Created
         */
        201: CommentResponse;
        /**
         * Unauthorized
         */
        401: ErrorResponse;
        /**
         * Not found
         */
        404: unknown;
      };
    };
  };
  "/comments/posts/{postId}": {
    get: {
      req: FindAllCommentsData;
      res: {
        /**
         * OK
         */
        200: Array<CommentResponse>;
        /**
         * Unauthorized
         */
        401: ErrorResponse;
        /**
         * Not found
         */
        404: unknown;
      };
    };
  };
  "/comments/{commentId}": {
    get: {
      req: FindCommentByIdData;
      res: {
        /**
         * OK
         */
        200: CommentResponse;
        /**
         * Unauthorized
         */
        401: ErrorResponse;
        /**
         * Not found
         */
        404: unknown;
      };
    };
    patch: {
      req: UpdateCommentData;
      res: {
        /**
         * OK
         */
        200: CommentResponse;
        /**
         * Unauthorized
         */
        401: ErrorResponse;
        /**
         * Not found
         */
        404: unknown;
      };
    };
    delete: {
      req: DeleteCommentData;
      res: {
        /**
         * No content
         */
        204: void;
        /**
         * Unauthorized
         */
        401: ErrorResponse;
        /**
         * Not found
         */
        404: unknown;
      };
    };
  };
  "/comments/{id}/vote": {
    post: {
      req: VoteCommentData;
      res: {
        /**
         * No content
         */
        204: void;
        /**
         * Unauthorized
         */
        401: ErrorResponse;
        /**
         * Not found
         */
        404: unknown;
      };
    };
  };
  "/comments/{id}/unvote": {
    delete: {
      req: UnvoteCommentData;
      res: {
        /**
         * No content
         */
        204: void;
        /**
         * Unauthorized
         */
        401: ErrorResponse;
        /**
         * Not found
         */
        404: unknown;
      };
    };
  };
  "/communities": {
    post: {
      req: CreateCommunityData;
      res: {
        /**
         * Created
         */
        201: Community;
        /**
         * Unauthorized
         */
        401: ErrorResponse;
      };
    };
    get: {
      res: {
        /**
         * OK
         */
        200: Array<Community>;
        /**
         * Unauthorized
         */
        401: ErrorResponse;
      };
    };
  };
  "/communities/{id}/membership": {
    get: {
      req: CheckUserMembershipData;
      res: {
        /**
         * OK
         */
        200: string;
        /**
         * Unauthorized
         */
        401: ErrorResponse;
        /**
         * Community not found
         */
        404: unknown;
      };
    };
  };
  "/communities/me": {
    get: {
      res: {
        /**
         * OK
         */
        200: Array<Community>;
        /**
         * Unauthorized
         */
        401: ErrorResponse;
      };
    };
  };
  "/communities/{id}": {
    get: {
      req: FindOneCommunityData;
      res: {
        /**
         * OK
         */
        200: Community;
        /**
         * Unauthorized
         */
        401: ErrorResponse;
        /**
         * Not found
         */
        404: unknown;
      };
    };
    patch: {
      req: UpdateCommunityData;
      res: {
        /**
         * OK
         */
        200: Community;
        /**
         * Unauthorized
         */
        401: ErrorResponse;
        /**
         * Not found
         */
        404: unknown;
      };
    };
    delete: {
      req: RemoveCommunityData;
      res: {
        /**
         * No content
         */
        204: void;
        /**
         * Unauthorized
         */
        401: ErrorResponse;
        /**
         * Not found
         */
        404: unknown;
      };
    };
  };
  "/communities/{id}/join": {
    post: {
      req: JoinCommunityData;
      res: {
        /**
         * No content
         */
        204: void;
        /**
         * Unauthorized
         */
        401: ErrorResponse;
        /**
         * Not found
         */
        404: unknown;
      };
    };
  };
  "/communities/{id}/leave": {
    post: {
      req: LeaveCommunityData;
      res: {
        /**
         * No content
         */
        204: void;
        /**
         * Unauthorized
         */
        401: ErrorResponse;
        /**
         * Not found
         */
        404: unknown;
      };
    };
  };
  "/posts/feed": {
    get: {
      req: GetFeedData;
      res: {
        /**
         * OK
         */
        200: Array<PostResponse>;
        /**
         * Unauthorized
         */
        401: ErrorResponse;
      };
    };
  };
  "/posts/{communityId}": {
    post: {
      req: CreatePostData;
      res: {
        /**
         * Created
         */
        201: PostResponse;
        /**
         * Unauthorized
         */
        401: ErrorResponse;
        /**
         * Not found
         */
        404: unknown;
      };
    };
  };
  "/posts/all": {
    get: {
      res: {
        /**
         * OK
         */
        200: Array<PostResponse>;
        /**
         * Unauthorized
         */
        401: ErrorResponse;
        /**
         * Not found
         */
        404: unknown;
      };
    };
  };
  "/posts/user/{userId}": {
    get: {
      req: FindAllPostsByUserData;
      res: {
        /**
         * OK
         */
        200: Array<PostResponse>;
        /**
         * Unauthorized
         */
        401: ErrorResponse;
      };
    };
  };
  "/posts/community/{communityId}": {
    get: {
      req: FindAllPostsInCommunityData;
      res: {
        /**
         * OK
         */
        200: Array<PostResponse>;
        /**
         * Unauthorized
         */
        401: ErrorResponse;
        /**
         * Not found
         */
        404: unknown;
      };
    };
  };
  "/posts/{id}": {
    get: {
      req: FindOnePostData;
      res: {
        /**
         * OK
         */
        200: PostResponse;
        /**
         * Unauthorized
         */
        401: ErrorResponse;
        /**
         * Not found
         */
        404: unknown;
      };
    };
    patch: {
      req: UpdatePostData;
      res: {
        /**
         * OK
         */
        200: PostResponse;
        /**
         * Unauthorized
         */
        401: ErrorResponse;
        /**
         * Not found
         */
        404: unknown;
      };
    };
    delete: {
      req: RemovePostData;
      res: {
        /**
         * No content
         */
        204: void;
        /**
         * Unauthorized
         */
        401: ErrorResponse;
        /**
         * Not found
         */
        404: unknown;
      };
    };
  };
  "/posts/{id}/vote": {
    post: {
      req: VotePostData;
      res: {
        /**
         * No content
         */
        204: void;
        /**
         * Unauthorized
         */
        401: ErrorResponse;
        /**
         * Not found
         */
        404: unknown;
      };
    };
  };
  "/posts/{id}/unvote": {
    delete: {
      req: UnvotePostData;
      res: {
        /**
         * No content
         */
        204: void;
        /**
         * Unauthorized
         */
        401: ErrorResponse;
        /**
         * Not found
         */
        404: unknown;
      };
    };
  };
  "/replies/{commentId}": {
    post: {
      req: CreateReplyData;
      res: {
        /**
         * Created
         */
        201: ReplyResponse;
        /**
         * Unauthorized
         */
        401: ErrorResponse;
        /**
         * Not found
         */
        404: unknown;
      };
    };
  };
  "/replies/comments/{commentId}": {
    get: {
      req: FindAllRepliesData;
      res: {
        /**
         * OK
         */
        200: Array<ReplyResponse>;
        /**
         * Unauthorized
         */
        401: ErrorResponse;
        /**
         * Not found
         */
        404: unknown;
      };
    };
  };
  "/replies/{replyId}": {
    get: {
      req: FindOneReplyData;
      res: {
        /**
         * OK
         */
        200: ReplyResponse;
        /**
         * Unauthorized
         */
        401: ErrorResponse;
        /**
         * Not found
         */
        404: unknown;
      };
    };
    patch: {
      req: UpdateReplyData;
      res: {
        /**
         * OK
         */
        200: ReplyResponse;
        /**
         * Unauthorized
         */
        401: ErrorResponse;
        /**
         * Not found
         */
        404: unknown;
      };
    };
    delete: {
      req: DeleteReplyData;
      res: {
        /**
         * No content
         */
        204: void;
        /**
         * Unauthorized
         */
        401: ErrorResponse;
        /**
         * Not found
         */
        404: unknown;
      };
    };
  };
  "/replies/{id}/vote": {
    post: {
      req: VoteReplyData;
      res: {
        /**
         * No content
         */
        204: void;
        /**
         * Unauthorized
         */
        401: ErrorResponse;
        /**
         * Not found
         */
        404: unknown;
      };
    };
  };
  "/replies/{id}/unvote": {
    delete: {
      req: UnvoteReplyData;
      res: {
        /**
         * No content
         */
        204: void;
        /**
         * Unauthorized
         */
        401: ErrorResponse;
        /**
         * Not found
         */
        404: unknown;
      };
    };
  };
};
